{{ include "common.storage.hostPathValidate" .Values }}
{{ include "common.deployment.common_config" . | nindent 0 }}
spec: {{ include "common.deployment.common_spec" . | nindent 2 }}
  template: {{ include "common.deployment.pod.metadata" . | nindent 4 }}
    spec:
    {{- if .Values.hostNetwork }}
      hostNetwork: {{ .Values.hostNetwork }}
      dnsPolicy: ClusterFirstWithHostNet
    {{- end }}
      hostname: {{ template "common.names.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          {{ include "common.resources.limitation" . | nindent 10 }}
          {{ include "common.containers.imageConfig" .Values.image | nindent 10 }}
          volumeMounts: {{ include "common.storage.configureAppVolumeMountsInContainer" .Values | nindent 12 }}
            - name: onnx-probe-check
              mountPath: /bin/onnx_probe_check.sh
              readOnly: true
              subPath: entrypoint.sh
          ports:
          - name: onnx
            protocol: TCP
            containerPort: 5000
          {{- if .Values.hostNetwork }}
            hostPort: {{ .Values.onnxServiceTCP.port }}
          {{- end }}
          env:
            - name: KUBE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            {{ $envList := (default list .Values.environmentVariables) }}
            {{ if and .Values.gpuConfiguration (hasKey .Values.gpuConfiguration "nvidia.com/gpu") (gt (get .Values.gpuConfiguration "nvidia.com/gpu" | toDecimal) 0) }}
            {{ $envList = mustAppend $envList (dict "name" "NVIDIA_DRIVER_CAPABILITIES" "value" "all") }}
            {{ end }}
            {{ $envList = mustAppend $envList (dict "name" "TZ" "value" .Values.timezone) }}
            {{ include "common.containers.environmentVariables" (dict "environmentVariables" $envList) | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            failureThreshold: 5
            periodSeconds: 15
            initialDelaySeconds: 15
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            failureThreshold: 5
            periodSeconds: 15
            initialDelaySeconds: 15
          startupProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            failureThreshold: 20
            periodSeconds: 15
            initialDelaySeconds: 15
      {{ include "common.networking.dnsConfiguration" .Values | nindent 6 }}
      volumes: {{ include "common.storage.configureAppVolumes" .Values | nindent 8 }}
        - name: onnx-probe-check
          configMap:
            defaultMode: 0700
            name: "onnx-probe-check"