appVolumeMounts:
  config:
    emptyDir: true
    mountPath: /config
  data:
    emptyDir: true
    mountPath: /data
  shared:
    emptyDir: true
    mountPath: shared
  shared-logs:
    emptyDir: true
    mountPath: /config/Library/Application Support/Plex Media Server/Logs
  transcode:
    emptyDir: true
    mountPath: /transcode
claimToken: ''
dnsConfig:
  options: []
emptyDirVolumes: true
enablePlexPass: false
environmentVariables: []
extraAppVolumeMounts:
- hostPath: /mnt/extras/hello
  mountPath: /mnt/extras
  readOnly: true
gpuConfiguration: {}
hostNetwork: false
image:
  pullPolicy: IfNotPresent
  repository: ssube/onnx-web-api
  tag: main-cuda-ubuntu
invokeaiServiceTCP:
  port: 5000
timezone: Etc/UTC
updateStrategy: Recreate
